export const sac9Brand = {
  primary: '#6F4AA8',
  primaryDark: '#5A378C',
  secondary: '#A6CE39',
  secondaryDark: '#8EB52F',
  gradient: 'linear-gradient(135deg, #6F4AA8 0%, #A6CE39 100%)',
} as const

export const sac9LightTheme = {
  background: '#F8FAFC',
  foreground: '#0F172A',
  card: '#FFFFFF',
  cardForeground: '#0F172A',
  popover: '#FFFFFF',
  popoverForeground: '#0F172A',
  primary: sac9Brand.primary,
  primaryForeground: '#FFFFFF',
  secondary: sac9Brand.secondary,
  secondaryForeground: '#172A0A',
  muted: '#EEF2F7',
  mutedForeground: '#64748B',
  accent: '#F1ECF8',
  accentForeground: sac9Brand.primaryDark,
  destructive: '#DC2626',
  border: '#E2E8F0',
  input: '#E2E8F0',
  ring: sac9Brand.primary,
  chart1: sac9Brand.primary,
  chart2: sac9Brand.secondary,
  chart3: '#2563EB',
  chart4: '#0EA5E9',
  chart5: '#8B5CF6',
} as const

export const sac9DarkTheme = {
  background: '#0F172A',
  foreground: '#E2E8F0',
  card: '#1E293B',
  cardForeground: '#E2E8F0',
  popover: '#1E293B',
  popoverForeground: '#E2E8F0',
  primary: sac9Brand.primary,
  primaryForeground: '#FFFFFF',
  secondary: sac9Brand.secondary,
  secondaryForeground: '#172A0A',
  muted: '#172033',
  mutedForeground: '#94A3B8',
  accent: '#2B2140',
  accentForeground: '#F1ECF8',
  destructive: '#F87171',
  border: '#334155',
  input: '#334155',
  ring: '#A78BFA',
  chart1: '#A78BFA',
  chart2: sac9Brand.secondary,
  chart3: '#60A5FA',
  chart4: '#38BDF8',
  chart5: '#C4B5FD',
} as const

export const kpiColors = {
  totalVendas: '#2563EB',
  ticketMedio: '#0EA5E9',
  lucro: sac9Brand.secondary,
  margemLucro: sac9Brand.secondaryDark,
  totalDescontos: sac9Brand.primary,
  quantidadeVendida: '#8B5CF6',
  projecaoMes: '#2563EB',
  quantidadeVendas: '#0EA5E9',
  pecasPorVenda: '#8B5CF6',
  mesmoPeriodoAnoAnterior: sac9Brand.primary,
  projecaoVsAnoAnterior: sac9Brand.secondaryDark,
} as const

export const chartPalette = [
  sac9Brand.primary,
  sac9Brand.secondary,
  '#2563EB',
  '#0EA5E9',
  '#8B5CF6',
  sac9Brand.primaryDark,
  sac9Brand.secondaryDark,
] as const
